import  com.springhow.examples.drools.domain.GrandOrderRequest;

rule "Discount for CARD payment above 10000"
    when
        orderObject : GrandOrderRequest( paymentType=="CARD" && totalPrice > 10000 );
    then
        orderObject.setDiscount(10);
end;

rule "Discount for CARD payment below 10000"
    when
        orderObject : GrandOrderRequest( paymentType=="CARD" && totalPrice > 5000 && totalPrice < 10000 );
    then
        orderObject.setDiscount(5);
end;
